### PR TITLE
fix nix build

### PR DESCRIPTION
**Pull request by TornaxO7**

### CODE REVIEW

**Review by raphamorim — APPROVED** [review]
👌

**Comment by TornaxO7** [comment]
peepoAwesome

**Comment by RaySlash** [comment]
@TornaxO7  Can I ask why did u do this PR? nix build already works.. You removing `(` and `) ` doesn't make a sensible change. Im confused. 👀

**Comment by TornaxO7** [comment]
> @TornaxO7 Can I ask why did u do this PR? nix build already works..

not on the main branch. I got
```
error: builder for '/nix/store/a0b900wb0m9kkdg41rq0yhh3lhcw84va-rio.drv' failed with exit code 101;
       last 10 log lines:
       >    Compiling rioterm-beta v0.1.0 (/build/gh0pw0231i063r2s8qbgjqhm11qf9zmc-source/frontends/rioterm-beta)
       > error[E0601]: `main` function not found in crate `rio_beta`
       >    --> frontends/rioterm-beta/src/main.rs:138:2
       >     |
       > 138 | }
       >     |  ^ consider adding a `main` function to `frontends/rioterm-beta/src/main.rs`
       >
       > For more information about this error, try `rustc --explain E0601`.
       > error: could not compile `rioterm-beta` (bin "rio-beta") due to previous error
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/a0b900wb0m9kkdg41rq0yhh3lhcw84va-rio.drv'.
error: 1 dependencies of derivation '/nix/store/4nk0l63casr2khcyxg3jml4740zqfqcj-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mvc3bjbgyi0ls8hgqx6cwlykjzsl4ccg-i3.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l6m7ck42v3qmhm95f6x8rl3cgkaa3rgk-home-manager-generation.drv' failed to build
```
from the latest changes in `main`.
>  You removing `(` and `) ` doesn't make a sensible change. Im confused. 👀

this was done from `nix fmt`

**Comment by TornaxO7** [comment]
now we've got a another problem:

image

I'll dig into it

**Comment by TornaxO7** [comment]
@RaySlash sorry for the quick change stuff. That was discussed on rio's discord server

**Pull request merged**
