### PR TITLE
fix: update version to 0.2.2 to match with the release

### PR DESCRIPTION
**Pull request by chenrui333**
👋 seeing some version issue when doing the homebrew release build.

relates to https://github.com/Homebrew/homebrew-core/pull/198769

cc @raphamorim

### CODE REVIEW

**Review by raphamorim — APPROVED** [review]
⭐ thank you @chenrui333

**Comment by chenrui333** [comment]
this is lighting fast!! :)

**Comment by chenrui333** [comment]
can you re-tag the release so that we can rebuild on the homebrew side, I have already verified the patch in my local.

**Comment by chenrui333** [comment]
thank you!! appreciate it.

**Comment by raphamorim** [comment]
pushed same tag over a new sha, thank you again 🙏

**Comment by chenrui333** [comment]
no worries, happy to help. 👍

**Pull request merged**
