### PR TITLE
minor suggestions on calculate_mouse_position functions.

### PR DESCRIPTION
**Pull request by inudev5**
its a minor refactoring suggestion to reduce function arguments.

### CODE REVIEW

**Comment by raphamorim** [comment]
Hey there @inudev5 thank you for the PR,

One of the reasons I implemented the way it was before was to avoid add `.clone()` to a function that's called/stacked a lot of times in a short span of interaction and also don't rely on sugarloaf layout contract.

Other point is that I want to get rid of clone usage in sugarloaf in the future, in general, using the clone method in Rust can be expensive in terms of performance because it creates a new instance of a value and copies all of its data. Rust has a few optimizations that can help reduce the cost of using the clone method but is good to avoid.

**Comment by inudev5** [comment]
@raphamorim  thank you for your answer! it helped me understand quite more.

**Comment by raphamorim** [comment]
🙏 I super appreciate the PR though!

Btw if you are looking for stuff to contribute on Rio (saw your comment on ligatures), I think these two issues are more welcoming to first time contribution:

- https://github.com/raphamorim/rio/issues/278
- https://github.com/raphamorim/rio/issues/267
- https://github.com/raphamorim/rio/issues/259

The third specially would be a huge contribution for Rio since the icons are rendered without any positioning.

**Comment by inudev5** [comment]
> 🙏 I super appreciate the PR though!
> 
> Btw if you are looking for stuff to contribute on Rio (saw your comment on ligatures), I think these three issues are more welcoming to first time contribution:
> 
> * [Scroll to fast in vim and nano #278](https://github.com/raphamorim/rio/issues/278)
> * [[Keybinding] ScrollLineDown/ScrollLineUp actions not work as expected #267](https://github.com/raphamorim/rio/issues/267)
> * [Sugarloaf: Positioning glyphs #259](https://github.com/raphamorim/rio/issues/259)
> 
> The third specially would be a huge contribution for Rio since the icons are rendered without any positioning.

I see. thanks.

**Pull request closed without merging**
