### PR TITLE
Add VI toggle for CTRL + SHIFT + SPACE on win

### LINKED ISSUE #462: bug: vi mode on Windows
on Windows, when Vi mode key pressed `Alt + Shift + Space`, it will launch menu instead.
image

Alacritty handle this well on Windows, but it have `Ctrl + Shift + Space` shortcut instead.

note: since I use tmux, this basically unneeded since in tmux there is copy mode

### PR DESCRIPTION
**Pull request by zackartz**
closes #462

### CODE REVIEW

**Comment by zackartz** [comment]
(i am zack on discord btw :)

**Comment by raphamorim** [comment]
Thank you for your pr!

Would you mind updating the docs regarding it?

**Comment by zackartz** [comment]
Sure thing! I also added the keybinding to the WA implementation as well

**Review by raphamorim — APPROVED** [review]
👍 thanks!!

**Pull request merged**
