### PR TITLE
feat: path based tab color coding

### PR DESCRIPTION
**Pull request by hougesen**
I really like the program based tab color coding, but I felt like it was missing the option to have path specified.

This feature allows the user to have 3 types of tab color coding:

- Program

```toml
[navigation]
color-automation = [{ program = "nvim", color = "#ff0000" }]
```

- Path

```toml
[navigation]
color-automation = [{ path = "/home/hougesen/.config/rio", color = "#00ff00" }]
```

- Program and path

```toml
[navigation]
color-automation = [
  { program = "nvim", path = "/home/hougesen/.config/rio", color = "#0000ff" },
]
```

I have not implemented the feature for Windows, since I do not have it installed.

You can see an example here (please don't mind the colors 😅)

TopTab example

I of course understand if this doesn't match the direction of the project. The call to `teletypewriter::foreground_process_path` will add some overhead, but personally I find it a lot easier to navigate my tabs using path based colors.

### CODE REVIEW

**Comment by raphamorim** [comment]
Hey @hougesen , I like a lot the idea but before proceed could you update the docs and changelog regarding the feature?

**Comment by raphamorim** [comment]
> The call to teletypewriter::foreground_process_path will add some overhead

It is ok, I was planning to use it for get the path to set the title as well as a configuration option.

**Comment by hougesen** [comment]
Coming right up in a moment :)

**Review by raphamorim — APPROVED** [review]
Great job @hougesen 🙏 Thanks for the contribution

**Pull request merged**
