### PR TITLE
Simplify logo

### PR DESCRIPTION
**Pull request by nix6839**
- Simplify logo
- Remove unnecessary files
- Update `.icns` file with [more format](https://gist.github.com/jamieweavis/b4c394607641e1280d447deed5fc85fc#saving-images) and new icon
- Update `.ico` files with more resolution(It would be nice to optimize for each deployment later) and new icon

### CODE REVIEW

**Review by raphamorim — APPROVED** [review]
🥇 great job again, liked the simplification of the logo.

**Review by raphamorim — APPROVED** [review]

**Comment by nix6839** [comment]
@raphamorim To see the source for this work and futuer tasks: https://www.figma.com/file/IH2wEVxPL1sxaVwQOvLXfs/Assets?type=design&node-id=0%3A1&mode=design&t=KJ0Z7eqG1exkMwCq-1

> 🥇 great job again, liked the simplification of the logo.

This was possible thanks to what you've built up!

**Comment by raphamorim** [comment]
Super appreciated 🙏 

The logo got a bit bigger in the website but the rest looks nice 👌 ✨ ✨ ✨ 

Screenshot 2023-11-06 at 00 42 33

Btw if you have any interest on keep working in the docs, looking forward for implement translations for the website https://github.com/raphamorim/rio/issues/324

**Comment by nix6839** [comment]
> Super appreciated 🙏
> 
> The logo got a bit bigger in the website but the rest looks nice 👌 ✨ ✨ ✨
> 
> Screenshot 2023-11-06 at 00 42 33

I must have missed it while separating the tasks 😥. I'll send a PR quickly.

> Btw if you have any interest on keep working in the docs, looking forward for implement translations for the website https://github.com/raphamorim/rio/issues/324

I'll translate Korean when I'm done with the index page redesign!

**Comment by raphamorim** [comment]
> I must have missed it while separating the tasks 😥. I'll send a PR quickly.

No worries at all! Just pushed the fix for it in main.

> I'll translate Korean when I'm done with the index page redesign!

That would be aweeeesome!! 🇰🇷

**Pull request merged**
