### PR TITLE
docs: markdown

### PR DESCRIPTION
**Pull request by bushuai**
1. Fix some image link issues.
2. Improve the formatting of tables, code blocks, and lists.

### CODE REVIEW

**Review by raphamorim — APPROVED** [review]
🎖️

**Comment by raphamorim** [comment]
@bushuai great job!
I was thinking in implement a GH action for deploy the docs on main (today it is manually deployed using `yarn deploy` on my machine 😢), would you like to contribute with it in a next PR?

**Comment by bushuai** [comment]
> @bushuai great job!
> 
> I was thinking in implement a GH action for deploy the docs on main (today it is manually deployed using `yarn deploy` on my machine 😢), would you like to contribute with it in a next PR?

Sure, I'll submit it later ✨

**Comment by raphamorim** [comment]
❤️

**Pull request merged**
