### PR TITLE
WIP: add basic touch support

### PR DESCRIPTION
**Pull request by androw**
#225 
First work on it
Need winit upgrade because of https://github.com/rust-windowing/winit/issues/3035

@raphamorim can you point me to the correct way to send click and cursor move event please?

### CODE REVIEW

**Comment by raphamorim** [comment]
Hey @androw,

That's great! So for the mouse Rio uses `mouse_position` function that does return a `Pos` https://github.com/raphamorim/rio/blob/65ffe901fdb3353e54860bc0daec8fdc4c286aff/rio/src/screen/mod.rs#L227-L250

With this `Pos` it uses `mouse_report` function that reports https://github.com/raphamorim/rio/blob/65ffe901fdb3353e54860bc0daec8fdc4c286aff/rio/src/screen/mod.rs#L1399-L1433

But I think for your case, you will need to use `on_left_click` function https://github.com/raphamorim/rio/blob/main/rio/src/screen/mod.rs#L1247-L1276 it receives the `Pos`, I think the biggest challenge here is translate touch into `Pos` (that's why I sent the mouse_position function before)

Note the mouse has a state called ClickState, it can be a click, double or triple. The click state is defined here https://github.com/raphamorim/rio/blob/main/rio/src/sequencer.rs#L438-L474

I think would be worth to make touch reuse the clickState though, then doesn't need to duplicate logic.

Keep in minde that `mouse_position` function is still not the best and needs to be fixed since whenever you change fonts it can lead to some issues (ref #182)

**Comment by androw** [comment]
If someone want to test and add feedback. We should have some basics working on X11 (for Wayland we need to wait for winit next version):
- select text
- zoom in/out
- scroll

**Comment by Nyabinary** [comment]
What version of Winit is needed, more specifically what commit? Because Rio uses the latest beta ver of Winit.

**Comment by androw** [comment]
> What version of Winit is needed, more specifically what commit? Because Rio uses the latest beta ver of Winit.

We need this commit https://github.com/rust-windowing/winit/commit/c2ed160e639ccaa10c6f0219e2cb25901aa559be which is not included in latest beta build.

**Comment by raphamorim** [comment]
@androw since we are already using the beta, I wouldn’t mind add winit dependency pointing to a git hash for the next build. Since in my experience Winit releases can take a while to wrap up (I know they are also considering a major refactor of how the event loop will work)

**Comment by Nyabinary** [comment]
That's seems like a solid idea tbh, could take advantage of some new features winit too if you point to the latest git hashes. Of course, it'll need proper testing, which I'll be happy to help with :)

**Comment by raphamorim** [comment]
@androw just a fyi, updated to winit 0.29.2 in main branch

**Comment by androw** [comment]
Working on Wayland without patch now!
But simple text selection is not working anymore. I might check this over the weekend

**Comment by raphamorim** [comment]
Niceee! thanks @androw let me know anything can help with :D and great job with it

**Comment by Nyabinary** [comment]
What the status on this?

**Comment by androw** [comment]
I've updated the branch and selection is still not working. I didn't have time to work on it and won't be able for some times.

**Comment by raphamorim** [comment]
No stress @androw, take your time on it 🙏 
@Nyabinary please don't comment like this, feels as pressure to release. It will come naturally 🙏

**Comment by Nyabinary** [comment]
> No stress @androw, take your time on it 🙏 @Nyabinary please don't comment like this, feels as pressure to release. It will come naturally 🙏

Oh, I was under the impression that it was ready to review, sorry! Should mark it as a draft PR too.

**Comment by raphamorim** [comment]
No stress @Nyabinary 🙏

**Comment by androw** [comment]
@raphamorim i do not fins what is wrong with my way of emulating a click. Can you have a look when you have some time?

**Comment by raphamorim** [comment]
> @raphamorim i do not find what's wrong with my way of emulating a click. Can you have a look when you have some time?

Of course, you are talking about the CI error?

**Comment by androw** [comment]
No (I haven't check the CI error yet).
For example, I'm using the following code to simulate a click
```
                route.window.screen.mouse.x = x;
                route.window.screen.mouse.y = y;

                let now = Instant::now();
                route.window.screen.mouse.last_click_timestamp =
                                            now;
                route.window.screen.mouse.last_click_button = MouseButton::Left;

                route.window.screen.mouse.click_state = ClickState::Click;
                route.window.screen.mouse.left_button_state = ElementState::Pressed;
                route.window.screen.on_left_click(route.window.screen.mouse_position(0));
```
and the following for releasing the click
```
            route.window.screen.mouse.click_state = ClickState::None;
            route.window.screen.mouse.left_button_state = ElementState::Released;
```
It used to work but it isn't (for example selection doesn't) since some changes on the main branch.
I think I'm not doing this the right way...

**Comment by raphamorim** [comment]
> It used to work but it isn't (for example selection doesn't) since some changes on the main branch.

Got it! Will take a look once I wrap the sixel protocol 🙏

**Comment by raphamorim** [comment]
@androw I've merged your changes into main (https://github.com/raphamorim/rio/commit/ae776054903e44de7b58465322eb6773d31e50ea). Overall the code does look fine for me (just added few updates in another commit), haven't tested properly the selection only the touch events but I will test before include to next release. Thank you for your work with it 🙏

**Pull request closed without merging**
