### PR TITLE
Testing msys2 release builds

### PR DESCRIPTION
**Pull request by Kreijstal**
We test to see if msys build runs on release!

### CODE REVIEW

**Comment by Kreijstal** [comment]
well I can defintely say it builds on clang

**Comment by Kreijstal** [comment]
@raphamorim Solved thanks to @ognevny

**Comment by raphamorim** [comment]
That's great! Amazing work @Kreijstal and thanks for the help @ognevny. I am actually considering to use `lto = true` for everything on release. Could you include this change on this PR?

**Review by raphamorim — APPROVED** [review]

**Comment by raphamorim** [comment]
Thank you @Kreijstal

**Pull request merged**
