### PR TITLE
Use as default thin lto instead to use full lto

### PR DESCRIPTION
**Pull request by NextWork123**
Hello, I noticed issue #737, and after some investigation, I would like to suggest switching from full LTO to ThinLTO. This change will optimize the compilation process more effectively than full LTO, resolve the compilation issues associated with it, and speed up the overall compilation time.

Best Regards,
NextWorks

### CODE REVIEW

**Comment by orhun** [comment]
Any idea why thin LTO resolves the compilation issues on Arch Linux?

FWIW: https://github.com/briansmith/ring/issues/1444

**Comment by NextWork123** [comment]
> Any idea why thin LTO resolves the compilation issues on Arch Linux?
> 
> FWIW: [briansmith/ring#1444](https://github.com/briansmith/ring/issues/1444)

some dependencies isn't passing with full lto (because of undefined symbols) so we need to switch to thin seem much packages on aur use thin as patch aswell i can put a patch in the pkgbuild and we can leave the full lto on all project errors about full lto:

https://paste.cachyos.org/p/eef0fd6.txt

let me know what i need to do

**Comment by orhun** [comment]
Yup, I think this should be solved on the Arch side of things instead of upstream.

We can keep the fat LTO and use the workaround mentioned in <https://github.com/briansmith/ring/issues/1444> - that's what we do for most of the Arch packages these days.

**Comment by NextWork123** [comment]
> Yup, I think this should be solved on the Arch side of things instead of upstream.
> 
> We can keep the fat LTO and use the workaround mentioned in [briansmith/ring#1444](https://github.com/briansmith/ring/issues/1444) - that's what we do for most of the Arch packages these days.

yeah, we can do that or switch the project to thin lto and remove the fat lto (isn't much safe as i said it do too lto on deps and other)

**Comment by NextWork123** [comment]
I gonna close the pull request as resolve for atleast arch linux management we can leave fat lto as default and leave the package managers fix that.

**Pull request closed without merging**
