### PR TITLE
Work in progress: Search

### LINKED ISSUE #162: Support searching
Similar to iTerm2 and Alacritty, can we have Cmd-F / Ctrl-F and be able to search for a string? Is it deemed a desirable feature?

So far I am loving Rio, seems to need a bit more love still.

### PR DESCRIPTION
**Pull request by raphamorim**
Closes #162

### CODE REVIEW

**Comment by orhun** [comment]
Happy to test this out on Linux, just lmk :)

**Comment by raphamorim** [comment]
@orhun merged into main but help me test there and we can evolve from other small PRs 🙏

**Comment by orhun** [comment]
I think this needs some docs updates, what is the default key binding for search?

**Comment by raphamorim** [comment]
Need to map these into actions on docs:

https://github.com/raphamorim/rio/blob/main/frontends/rioterm/src/bindings/bindings_winit/mod.rs#L219-L234

**Comment by raphamorim** [comment]
default bindings btw https://github.com/raphamorim/rio/blob/main/frontends/rioterm/src/bindings/bindings_winit/mod.rs#L1029-L1034

**Pull request merged**
